#!/bin/bash

cd ..
git checkout -B gh-pages
git add -f site/public
git commit -am "Rebuild website"
git filter-branch -f --prune-empty --subdirectory-filter site/public
git push -f origin gh-pages
git checkout -
cd site
