#!/usr/bin/env node

'use strict'

var bs = require("browser-sync").create()
var exec = require('child_process').exec

// .init starts the server
bs.init({
  open   : false,
  server : "./public"
})

function make () {
  exec('make -sj', function (error, stdout, stderr) {
    if (error) {
      console.error(`exec error: ${error}`)
      return
    }

    if (stdout) {
      console.log(stdout)
    }

    if (stderr) {
      console.error(stdout)
    }

    bs.reload()
  })
}


bs.watch('src/**/*').on('change', make)
bs.watch('../docs/**/*').on('change', make)
